# Generated by Django 6.0 on 2025-12-10 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status', models.CharField()),
                ('is_tutor_candidate', models.BooleanField()),
                ('current_location', models.CharField()),
                ('career_focus', models.TextField()),
                ('dob', models.DateField()),
                ('profile_picture', models.ImageField(upload_to='')),
                ('email_verification', models.BooleanField()),
                ('registration_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
