# Generated by Django 6.0 on 2025-12-11 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexuspro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ccna', 'CCNA/Network Tutoring'), ('ccnp', 'CCNP Advanced Training'), ('cyber', 'Cyber Security'), ('onsite', 'On-Site Technician'), ('remote', 'Remote IT Support'), ('cv_career', 'CV & Career Optimization'), ('biz_reg', 'Business Registration'), ('web_dev', 'Software Development')], max_length=50)),
                ('details', models.TextField()),
                ('location', models.CharField(blank=True, help_text='Required for On-Site services.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Confirmed', 'Confirmed & Scheduled'), ('Completed', 'Service Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('session_date', models.DateTimeField(blank=True, help_text='Date and time when the session is scheduled.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('service_interest', models.CharField(choices=[('networking', 'Networking & Labs (CCNA/CCNP)'), ('security', 'Cyber Security'), ('career', 'Career/CV Advisory'), ('business', 'Business Registration'), ('software', 'Software Development')], default='networking', max_length=30)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('service_provided', models.CharField(help_text='e.g., CCNP Training, CV Optimization', max_length=100)),
                ('quote', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
