"""
Django settings for NexusProSolutions project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url # <--- ADD THIS IMPORT

#M-PESA API INTEGRATION START
# settings.py

# --- MPESA CONFIGURATION ---
from decouple import config # Make sure 'from decouple import config' is at the top

MPESA_CONSUMER_KEY = config('MPESA_CONSUMER_KEY')
MPESA_CONSUMER_SECRET = config('MPESA_CONSUMER_SECRET')
MPESA_SHORTCODE_STK = config('MPESA_SHORTCODE_STK', default='174379')
MPESA_PASSKEY = config('MPESA_PASSKEY')
MPESA_API_BASE_URL = config('MPESA_API_BASE_URL', default='https://sandbox.safaricom.co.ke/mpesa/')



#END OF M-PESA API INTEGRATION





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8vm%^eq%*)9m$8i@j@dok@3dtyw(a7ewgn$s+qm+yjm=3h-ks%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  #FOR PRODUCTION ENVIRONMENT

ALLOWED_HOSTS = ['.render.com', 'localhost', '127.0.0.1']

#<--- Other security settings you may need:--->
SECURE_HSTS_SECONDS = 2592000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

#<---END OF OTHER SECURITY SETTINGS FOR PRODUCTION ENVIRONMENT--->


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nexuspro',
    'widget_tweaks', #for widgets
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #<--ADDED BELOW FOR PRODUCTION ENVIRONMENT IN RENDER WITH DIFFERENT DATABASE-->
    'whitenoise.middleware.WhiteNoiseMiddleware',
          # <---END OF ADDED--->
]   

ROOT_URLCONF = 'NexusProSolutions.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NexusProSolutions.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# settings.py (Production Ready)
# 4. Database Configuration
DATABASES = {
    'default': dj_database_url.config(
        # Looks for the DATABASE_URL environment variable (from Render)
        # If not found (running locally), it defaults back to SQLite3
        default=os.environ.get('DATABASE_URL', 'sqlite:///db.sqlite3'),
        conn_max_age=600 # Enables connection pooling for performance
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR, 'static'
]

# settings.py

# 3. Static Files Configuration for Whitenoise
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# settings.py

# CRITICAL FIX: Tell Django the correct URL for the user dashboard.
# Your URL name for the dashboard is 'profile', mapped to the path 'profile/'.
LOGIN_REDIRECT_URL = '/profile/' 

# Ensure the login path is also defined (it usually defaults to this)
LOGIN_URL = '/login/'





#SWITCHING FROM SQLITE3 TO PostgreSQL FOR HOSTING IN RENDER 
